### ISSUE TITLE
[BUG] - `python-auth0` version `4.0.0` introduces breaking changes

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1623]
### Describe the bug

Nebari can integrate with Auth0 and as such uses the `python-auth0` package. Two hours ago, Auth0 released a new version (4.0.0) which introduced a few breaking changes. ([See their migration guide for details](https://github.com/auth0/auth0-python/blob/master/V4_MIGRATION_GUIDE.md)). 

Now, when using the `nebari` CLI (with `python-auth0==4.0.0`), you will see the following error message:

```
Traceback (most recent call last):
  File "/Users/eskild/miniconda3/envs/nebari/bin/nebari", line 5, in <module>
    from nebari.cli.main import app
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/nebari/cli/main.py", line 13, in <module>
    from nebari.cli.init import (
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/nebari/cli/init.py", line 9, in <module>
    from nebari.initialize import render_config
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/nebari/initialize.py", line 13, in <module>
    from nebari.provider.oauth.auth0 import create_client
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/nebari/provider/oauth/auth0.py", line 4, in <module>
    from auth0.v3.authentication import GetToken
ModuleNotFoundError: No module named 'auth0.v3'
```

### Expected behavior

We expect the CLI to work.

### OS and architecture in which you are running Nebari

MacOS - all versions of Nebari

### How to Reproduce the problem?

Try `pip` installing `nebari` and then try and use the CLI.

### Anything else?

Since we don't pin `python-auth0`, all past versions of Nebari that are now installed, will run into this issue. This is even more troublesome given that our GitOps workflows (linting and deploying) pip install nebari each time they run and therefore will no longer work.

**Comment by ericdatakelly** [comment]
I also ran into this error when trying to install locally (Ubuntu/pop_os 22.04).  I pinned `auth0-python` to 3.24.0 but got import errors when running `nebari --help`.  I also tried pinning python to older versions (3.9, 3.8), but continued to get import errors.
