### ISSUE TITLE
[BUG] - Panel periodic callback prevents idle culler from shutdown

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1687]
### Describe the bug

I was using a Panel app inside of a jupyter notebook (`pn.state.add_periodic_callback(self.periodic_trigger, period=1000)`). This kept my Nebari instance alive almost 4 days without my browser even having the nebari page open. 

From the k9s logs, it looks like the idle culler attempted to cull, but because of an error in the callback, it was prevented...?

```
│ notebook [W 2023-03-28 08:29:21.882 SingleUserNotebookApp kernelmanager:484] Culling 'idle' kernel 'python3' (5517217b-62d7-49f8-a627-7246892a02e9) with 2 connections due to 1174 seconds of inactivity.              │
│ notebook [I 2023-03-28 08:29:21.883 SingleUserNotebookApp multikernelmanager:242] Kernel shutdown: 5517217b-62d7-49f8-a627-7246892a02e9                                                                                │
│ notebook [I 2023-03-28 08:29:28.392 SingleUserNotebookApp kernelmanager:286] Discarding 221970 buffered messages for 6d09eecd-30bf-48c2-8eaa-efa354079269:99cf921b-0ae3-476b-8055-7229ff611d75                         │
│ notebook [I 2023-03-28 08:29:28.612 SingleUserNotebookApp kernelmanager:222] Starting buffering for 6d09eecd-30bf-48c2-8eaa-efa354079269:dbae821f-79e9-4c7a-82df-19f9bee5c236                                          │
│ notebook 2023-03-28 08:29:37,886 - SingleUserNotebookApp - ERROR - Uncaught exception GET /user/kcpevey@quansight.com/api/metrics/v1/kernel_usage/get_usage/6d09eecd-30bf-48c2-8eaa-efa354079269?1680010177692 (10.32. │
│ notebook HTTPServerRequest(protocol='http', host='nebari.quansight.dev', method='GET', uri='/user/kcpevey@quansight.com/api/metrics/v1/kernel_usage/get_usage/6d09eecd-30bf-48c2-8eaa-efa354079269?1680010177692', ver │
│ notebook Traceback (most recent call last):                                                                                                                                                                            │
│ notebook   File "/opt/conda/envs/default/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute                                                                                                          │
│ notebook     result = await result                                                                                                                                                                                     │
│ notebook   File "/opt/conda/envs/default/lib/python3.10/site-packages/jupyter_resource_usage/api.py", line 127, in get                                                                                                 │
│ notebook     res = await client.control_channel.get_msg(timeout=0)                                                                                                                                                     │
│ notebook TypeError: object dict can't be used in 'await' expression                                                                                                                                                    │
│ notebook [E 2023-03-28 08:29:37.886 SingleUserNotebookApp web:1798] Uncaught exception GET /user/kcpevey@quansight.com/api/metrics/v1/kernel_usage/get_usage/6d09eecd-30bf-48c2-8eaa-efa354079269?1680010177692 (10.32 │
│ notebook     HTTPServerRequest(protocol='http', host='nebari.quansight.dev', method='GET', uri='/user/kcpevey@quansight.com/api/metrics/v1/kernel_usage/get_usage/6d09eecd-30bf-48c2-8eaa-efa354079269?1680010177692', │
│ notebook     Traceback (most recent call last):                                                                                                                                                                        │
│ notebook       File "/opt/conda/envs/default/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute                                                                                                      │
│ notebook         result = await result                                                                                                                                                                                 │
│ notebook       File "/opt/conda/envs/default/lib/python3.10/site-packages/jupyter_resource_usage/api.py", line 127, in get                                                                                             │
│ notebook         res = await client.control_channel.get_msg(timeout=0)                                                                                                                                                 │
│ notebook     TypeError: object dict can't be used in 'await' expression                                                                                                                                                │
│ notebook [W 2023-03-28 08:29:37.887 SingleUserNotebookApp handlers:649] wrote error: 'Unhandled error'                                                                                                                 │
│ notebook [W 2023-03-28 08:29:37.888 SingleUserNotebookApp client:121] Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fdfe58fde70> 
```

### Expected behavior

I expect my Nebari server to be killed by the idle culler. 

### OS and architecture in which you are running Nebari

GCP 

### How to Reproduce the problem?

Run a periodic callback with something like this `pn.state.add_periodic_callback(self.periodic_trigger, period=1000)` where `self.periodic_trigger` is a functionn

### Compute environment

None

**Comment by viniciusdc** [comment]
Thanks, @kcpevey; after some debugging, the issue above, as reported [here](https://github.com/jupyter-server/jupyter-resource-usage/pull/177), and has been fixed already, with the addition of [this fix as well](https://github.com/jupyter-server/jupyter-resource-usage/issues/182).  As of now, no release fixes all of the problem related, but the best curse of action as of now is bumping the current version of whenever resources whose dependency is `jupyter-resource-package`

**Comment by viniciusdc** [comment]
We are waiting for a new release of `jupyter-resource-package` that will have the fix for this issue

**Comment by kcpevey** [comment]
Note that this issue could have been affected by https://github.com/nebari-dev/nebari/issues/1902

**Comment by kcpevey** [comment]
Closing since this is likely resolved and also we no longer use CDS Dashboards.
