### ISSUE TITLE
[BUG] - Broken Local Integration Tests CI

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2381]
### Describe the bug

Logging in with the latest "main" images from nebari-docker-images repo on the jupyterhub pod yields the 500: Internal Server Error page.  The logs from the jupyterhub pod are 
```
│ [E 2024-04-04 16:14:38.225 JupyterHub web:1875] Uncaught exception GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5MTlmOWQ0ZjNiOGU0MDFiODBhNjE2ZWYwYjcwOGQwYSJ9&session_state=5aa83245-4797-47aa-aa58-75a573 │
│     HTTPServerRequest(protocol='http', host='github-actions.nebari.dev', method='GET', uri='/hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5MTlmOWQ0ZjNiOGU0MDFiODBhNjE2ZWYwYjcwOGQwYSJ9&session_state=5aa83245- │
│     Traceback (most recent call last):                                                                                                                                                                         │
│       File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute                                                                                                                     │
│         result = await result                                                                                                                                                                                  │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 210, in get                                                                                                                 │
│         user = await self.login_user()                                                                                                                                                                         │
│       File "/opt/conda/lib/python3.9/site-packages/jupyterhub/handlers/base.py", line 916, in login_user                                                                                                       │
│         authenticated = await self.authenticate(data)                                                                                                                                                          │
│       File "/opt/conda/lib/python3.9/site-packages/jupyterhub/auth.py", line 493, in get_authenticated_user                                                                                                    │
│         authenticated = await maybe_future(self.authenticate(handler, data))                                                                                                                                   │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 1029, in authenticate                                                                                                       │
│         token_info = await self.get_token_info(handler, access_token_params)                                                                                                                                   │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 874, in get_token_info                                                                                                      │
│         token_info = await self.httpfetch(                                                                                                                                                                     │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 688, in httpfetch                                                                                                           │
│         return await self.fetch(                                                                                                                                                                               │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 654, in fetch                                                                                                               │
│         raise e                                                                                                                                                                                                │
│       File "/opt/conda/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 633, in fetch                                                                                                               │
│         resp = await self.http_client.fetch(req, **kwargs)                                                                                                                                                     │
│     tornado.curl_httpclient.CurlError: HTTP 599: SSL certificate problem: self signed certificate   
```

### Expected behavior

No error

### OS and architecture in which you are running Nebari

Linux

### How to Reproduce the problem?

See above

### Compute environment

None

**Comment by Adam-D-Lewis** [comment]
Fixed by https://github.com/nebari-dev/nebari/pull/2361
